# Generated by Django 5.2.1 on 2025-05-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izexam',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Изображение задания'),
        ),
    ]
